### ISSUE TITLE
Not translating 

### ISSUE THREAD

**Issue by MercifulSavage** [NotMyself/Louie#2]
The bot is no longer working, it's not translating but the commands are still being established.

**Comment by AlooAkbar** [comment]
Hi @MercifulSavage . I had the same problem. I'm new to nodejs but from what I can tell it's an issue with the google-translate-api package from npm. The same issue described [here] (https://github.com/matheuss/google-translate-api/issues/79)

I forked the repo and changed the package.json to use `"google-translate-api": "vitalets/google-translate-api",`
I also encountered an error with unescaped single quotes in the seconds-converter package. The same one described [here] (https://github.com/nmajor25/seconds-converter/issues/3) . So for that as well I updated the package.json with a forked, fixed version `"seconds-converter": "AlooAkbar/seconds-converter",`

Now it's working great! Thanks for all the hard work @NotMyself, and thanks for keeping it free.

**Comment by NotMyself** [comment]
Hey @AlooAkbar shoot me a PR and I'll merge it. I have been traveling the last week and have not had a chance to deal with this.

**Comment by AlooAkbar** [comment]
@NotMyself no problem

**Comment by MercifulSavage** [comment]
Thanks! Yes, @NotMyself, thank you for all your hard work and keeping it free. Really is a huge life saver for me <3
